name: "build"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Cache /nix/store
      uses: actions/cache@v1
      with:
        path: /nix/store
        key: ${{ matrix.os }}-nix-store
    - name: Install nix
      uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: false
    - name: Build
      run: nix-build --max-jobs 2
