name: "build"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc: [ghc865, ghc882]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: nix-build --argstr compiler ${{ matrix.ghc }} --max-jobs 10
